### ISSUE TITLE
Exclude images warnings from certain addon types

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#11]
The following types should only have icon.png as mandatory
- Modules
- Context
- font
- language

Might be others out there?

**Comment by Razzeee** [comment]
`metadata.` maybe?

What's the folder name for fonts anyway?

**Comment by Razzeee** [comment]
Added some here https://github.com/xbmc/addon-check/commit/749ab0cbaa6c42a30b5e4f33bd3acbcae59ac4e7

**Comment by Razzeee** [comment]
Closing this, until somebody tells me what else to exclude.
