### ISSUE TITLE
[RFC] Should an optional dependency be reported as a problem?

### ISSUE THREAD

**Issue by enen92** [xbmc/addon-check#110]
Ref: https://github.com/xbmc/repo-plugins/pull/2001

script.module.inputstreamhelper is an optional dependency of the youtube addon and only makes sense for v17+. Youtube is in the isengard repo and is able to operate even without inputstream.

Question is...should we report such cases as problem? IMO warning fits better if the dependency is optional.

**Comment by Rechi** [comment]
IMO even warning is too high, maximum is INFO. Setting a dependency as optional requires additional changes in addon.xml so the author should be aware of what it means.

**Comment by Razzeee** [comment]
yeah, we should honor the optional flag.
