### ISSUE TITLE
requirements.txt doesn't seem to be included in pypi package

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#119]
`requirements.txt` doesn't seem to be shipped and thus can't be read on install.

https://travis-ci.org/Razzeee/script.trakt/jobs/439924791

**Comment by tiagovizoto** [comment]
Do have Project support to 2.7.0 version? 
You log show python 2.7.0

**Comment by sichuan-pepper** [comment]
You should add MANIFEST.in file and include requirements.txt.

**Comment by Rechi** [comment]
Use one of the supported python versions.

https://github.com/xbmc/addon-check/blob/8602821f23641bbe34a2473d445e8c31a3094888/setup.py#L38

**Comment by Razzeee** [comment]
Thanks all!
