### ISSUE TITLE
Add check for orphaned add-on 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#124]
Over time some add-ons might become broken/obsolete and will be removed. Some have a certain helper add-on which we then also forget to remove. Would be nice if we could detect this in some way if there are any. This can be done in the general scan on each branch and doesn't need to bother the regular submission report.

**Comment by mzfr** [comment]
What do you mean by `helper` add-on? Does it mean addons present in the `require` section of the addon.xml? Can you please provide an example of an addon

**Comment by MartijnKaijser** [comment]
Indeed one that is marked as required by other add-ons.
Almost all module scripts are helper add-on as they do not function on their own but are called by some other script/plugin

**Comment by MartijnKaijser** [comment]
yes a module can be used by multiple addons however in the end it might not used at all anymore.
So any *.module.* needs to be added as dependency at least once for any addon
