### ISSUE TITLE
strip travis build paths from log

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#13]
Maybe strip the travis paths from the log outputs like 
`
PROBLEM: Invalid xml found. /home/travis/build/xbmc/repo-plugins/plugin.video.reddit_viewer/resources/settings.xml`

**Comment by Razzeee** [comment]
Hrm, it's quite useful, if you run it locally. But I guess we could remove that fixed travis string?

**Comment by Razzeee** [comment]
Any feedback?

**Comment by mzfr** [comment]
@MartijnKaijser Any update on this? what @Razzeee has suggested seems okay. We could show the full paths when running locally, but not print them when running on Travis.

**Comment by Rechi** [comment]
The script already prints `Repo path ...` at the beginning, so IMO we can always strip it in all further output.
