### ISSUE TITLE
Allow empty tags in addon.xml

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#133]
Some one decided that empty tags like website,forum,email are not allowed. That's just wrong and needs to be fixed as they are perfectly valid.

**Comment by MartijnKaijser** [comment]
fyi this is a high priority fix cause the wiki actually states that these tags are kind of required and currently the add-on checks states the opposite

**Comment by Razzeee** [comment]
So it's just website, forum and email that need to be reverted?
https://github.com/xbmc/addon-check/pull/118/commits/56d3b9fac8a06d442bdf76d7f722f8e2a58de25e

**Comment by Razzeee** [comment]
Then again, I would love for broken to be forced to be filled. Same for license.

Why is this required? Or is this a case of us just not wanting to change the wiki (and/or the fallout)?

**Comment by MartijnKaijser** [comment]
Lets ask the opposite. Why is it disallowed to have an empty tag?

**Comment by learningit** [comment]
I guess the ultimate check for license is the actual license file itself, otherwise I would think license shouldn't be empty.

**Comment by MartijnKaijser** [comment]
Yes some are indeed mandatory and other are allowed to be empty. However forcing devs to remove empty tags should not be made compulsory

**Comment by learningit** [comment]
Agreed

**Comment by enen92** [comment]
Can we agree on what tags may be empty? In my opinion:

**Required not empty if used:**
- broken
- news
- source
- license

**May be empty:** (but we should report that they could be filled)
- email
- forum

I still do not understand why this was done. Has it something to do with the wiki or the addon-website?
