### ISSUE TITLE
Add license header to python files in add-on check

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#134]
It's encouraged that every python (or whatever) file has a short license reference at the top. 

>  Copyright (C) 2018-2018 Team Kodi
  This file is part of Kodi - https://kodi.tv
>
>  SPDX-License-Identifier: GPL-3.0-only
  See LICENSES/README.md for more information.

**Comment by mzfr** [comment]
@MartijnKaijser This one is connected to #126 
So now we want to first check if the license exists or not and if it doesn't then we just add it?

**Comment by MartijnKaijser** [comment]
It's not connected. Add-on checks itself also needs a license header in the Py files

**Comment by mzfr** [comment]
oh, you mean like files in this tool. I thought we have to add it when we are checking the addons. Sorry, my bad :)
