### ISSUE TITLE
Only check modified addons in a PR run

### ISSUE THREAD

**Issue by Rechi** [xbmc/addon-check#16]
It isn't useful to check all addons as one has to look at the log if the reason for a failing check is caused by the changed addon or by some other addon.

**Comment by Razzeee** [comment]
Might be possible to generate a list of changed toplevel folders via git foo, but haven't tried that yet.

**Comment by Rechi** [comment]
The command to get the toplevel changes is `git diff --name-only HEAD~ | cut -d / -f1 | sort | uniq`.

**Comment by Rechi** [comment]
If you could adjust the `check_repo.py` script to accept addon names like the above git command gives it would be great.
I can then adjust the travis files in the repos later.
