### ISSUE TITLE
Switching PEP style guideline check from pycodestyle to pylint.

### ISSUE THREAD

**Issue by LordGameleo** [xbmc/addon-check#173]
> Well it's running on the ci https://travis-ci.org/xbmc/addon-check/jobs/494757150#L520
Maybe we have something misconfigured or we just switch to pylint.

_Originally posted by @Razzeee in https://github.com/xbmc/addon-check/issues/168#issuecomment-469486822_

**Comment by LordGameleo** [comment]
@Razzeee Should I start working on this issue?

**Comment by Razzeee** [comment]
I would recommend to wait until https://github.com/xbmc/addon-check/pull/172 is merged

**Comment by mzfr** [comment]
@LordGameleo I'll complete the work on that PR by tonight.

**Comment by LordGameleo** [comment]
I will submit it as early as possible

**Comment by LordGameleo** [comment]
@Razzeee I am closing this issue and creating new issues which solves particular problem of pylint checks we disabled
