### ISSUE TITLE
Remove unused import and variables from all modules.

### ISSUE THREAD

**Issue by LordGameleo** [xbmc/addon-check#180]
We are currently using a customized checklist for pylint. We have disabled a lot of checks to make our build successfully. We want to counter these checks few at a time. This issue deals with one of them.

## How to produce:

After forking and cloning this repo, make a branch named develop-Pylint_rm_unused using
``git branch develop-Pylint_rm_unused``

Checkout branch by
``git checkout develop-Pylint_rm_unused``

remove  ```unused-import,``` and ```unused-variable,``` from .pylintrc file (line 24)

Check pylint errors using 
``pylint *`` on terminal (in the repo)

Add doc strings to get a perfect 10 score on pylint.

**Comment by Rechi** [comment]
already done
