### ISSUE TITLE
 Correct the mentioned pylint errors to get perfect 10(redefined-outer-name)

### ISSUE THREAD

**Issue by LordGameleo** [xbmc/addon-check#184]
We are currently using a customized checklist for pylint. We have disabled a lot of checks to make our build successfully. We want to counter these checks few at a time. This issue deals with one of them.

## How to produce:

After forking and cloning this repo, make a branch named develop-Pylint_Issue#184 using
``git branch develop-Pylint_Issue#184``

Checkout branch by
``git checkout develop-Pylint_Issue#184``

remove  ```redefined-outer-name``` from .pylintrc file 

Check pylint errors using 
``pylint *`` on terminal (in the repo)

Add doc strings to get a perfect 10 score on pylint.

**Comment by shrawnz** [comment]
Hi, I'd like to pick up this issue

**Comment by LordGameleo** [comment]
@shrawnz Try to finish previously assigned issues before proceeding. Please check reviewed changes for your PR.

**Comment by LordGameleo** [comment]
@Rechi why did you close this issue? Is it done in some PR?
