### ISSUE TITLE
How do I even run this application?

### ISSUE THREAD

**Issue by leopheard** [xbmc/addon-check#197]
**pip kodi-addon-checker path-to-folder-with-addon-in** doesn't work

**Comment by mzfr** [comment]
Why are you using `pip` in the starting of the command.

Pip should be used to install this.
To use this run ` kodi-addon-checker path-to-addon`

**Comment by leopheard** [comment]
I've already installed it. 

kodi-addon-checker path-to-addon gives "ERROR: unknown command "kodi-addon-checker".

**Comment by Razzeee** [comment]
sounds like it was no added to your path, by the installation method. or maybe you installed with for another user? maybe as root?
