### ISSUE TITLE
Feature: Ignore .tox and test/ directories

### ISSUE THREAD

**Issue by dagwieers** [xbmc/addon-check#198]
Currently the tool takes all files into account, even files that are not part of the plugin itself (like supporting infrastructure, its own kodi-addon-checker logfiles or build tools).

The add-on should not assume all files are part of the plugin, and should stick to the files that actually belong to what is distributed. Either by listing those files only (starting from addon.xml) or by accepting a ZIP file instead (so we can first create the ZIP file and then provide it to the tool).

In any case, it should exclude .tox/ and test/ directories to start with so people can use it as part of their development cycle.

**Comment by dagwieers** [comment]
Example output that should not be a problem:
```
ERROR: ./plugin.video.vrt.nu/Build-Zip.ps1 is marked as stand-alone executable
ERROR: ./plugin.video.vrt.nu/test/run.py is marked as stand-alone executable
--snip--
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/kodi-addon-checker-report.log
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/kodi-addon-checker.log
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/Build-Zip.ps1
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/test/userdata/vrtloginrt.tkn
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/test/userdata/XVRTToken.tkn
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/test/userdata/ondemand_vrtPlayerToken.tkn
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/test/userdata/live_vrtPlayerToken.tkn
WARN: Found non whitelisted file ending in filename ./plugin.video.vrt.nu/test/userdata/user_XVRTToken.tkn
```

**Comment by anxdpanic** [comment]
For the logs, run from out of directory.
With travis, most could be resolved as well. ex. https://github.com/jdf76/plugin.video.youtube/blob/master/.travis.yml 
https://travis-ci.org/jdf76/plugin.video.youtube/builds/558284685
Cloning master may not be wanted but is easily changed.

**Comment by Razzeee** [comment]
Both types of files you mention are files that are not necessary for your production build. And one use of this tool is to help making repo checks easier. Reporting on files that should not be included should be a part of this. For e.g. we don't want you to send executeables or powershell scripts, as inclusion would lead to the repo sending these to every user. Causes more to review for us, more bandwith use and more space used for the users.

**Comment by dagwieers** [comment]
@Razzeee Ignoring my feedback makes the tool unfit for other uses than one specific use-case. And that is fine, but disappointing, as the tool could be useful for more than just that, if you would be open to it. A new option would have sufficed.

(i.e. we don't have powershell scripts or tox files in our build, but the ability to test a source repository, even in Travis, helps addon developers IMO)

**Comment by Razzeee** [comment]
What I meant to highlight in my previous post is that this needs to be context aware. Runs on repos should always be sensitive to these files.

Runs on single addons need to be configurable. You want to both, have travis not fail in day to day and maybe have a release config that checks a tag you created (that might be too late) so you can be sure not to hit that problem when you send the addon.

**Comment by dagwieers** [comment]
> For the logs, run from out of directory.

Maybe add an option to not have logs? Travis output or console output is my log.

**Comment by Razzeee** [comment]
Should be available via the reporter option https://github.com/xbmc/addon-check/blob/8ab6f49768a12063575627c50022ee4713d475db/kodi_addon_checker/config.py#L64
Still docs might need improving
