### ISSUE TITLE
Travis sends failure emails although github has green checkmark 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#20]

**Comment by Rechi** [comment]
I think that is caused by the failing branches.
For PRs only the changed addons are checked to  not confuse the author (and us), for a branch run all addons are checked.

**Comment by Razzeee** [comment]
That's correct @Rechi

**Comment by mzfr** [comment]
@Razzeee Is this fixed? or is something still left to do? not really sure.

**Comment by Razzeee** [comment]
Well the example code has been updated, but not sure if we changed that for the repos where we run this already.

**Comment by Razzeee** [comment]
So I updated every known `.travis.yml` to include the email rule. So we should only get mails on changed status from now on. Let's see if it improves.

**Comment by mzfr** [comment]
@Razzeee if everything seems ok with this then we should close this issue

**Comment by mzfr** [comment]
@MartijnKaijser @Razzeee Are we still getting those emails ?

**Comment by Razzeee** [comment]
@MartijnKaijser will just reopen it if it still bothers him
