### ISSUE TITLE
Checker should error out if no en_gb file is found in translation 

### ISSUE THREAD

**Issue by enen92** [xbmc/addon-check#238]
The addon checker should error out if the addon is using the new folder language layout and doesn't include a en_gb strings.po file. This is the case of @sarbes plugin.audio.wdr3konzert/ in matrix where en_US is included: https://github.com/xbmc/repo-plugins/tree/matrix/plugin.audio.wdr3konzert/resources/language. en_GB is the default language for kodi since krypton, so it's presence if the addon includes localized strings is mandatory. Not including it and requiring translations, make the listitem labels empty

I'll pick this one myself once I find some time

**Comment by Space2Walker** [comment]
I have a somewhat related issue.
The addonchecker should error with a broken path to the strings.po file, and not say 
"INFO: PO files are valid" when kodi cant load them. For more info's see [Kodi-Forum](https://forum.kodi.tv/showthread.php?tid=357782).

**Comment by anxdpanic** [comment]
I have this staged locally to resolve both issues, needs some refactoring to satisfy pylint. will PR when I have it ready

**Comment by Space2Walker** [comment]
Thanks for the quick response and fix @anxdpanic.
