### ISSUE TITLE
Where is the advised version documented?

### ISSUE THREAD

**Issue by ReenigneArcher** [xbmc/addon-check#269]
I am trying to determine where the advised version is documented, as I want to set the version dynamically in my build scripts.

According to `repo-scripts`, they use 3.0.0 for `xbmc.python`.
https://github.com/xbmc/repo-scripts/blob/a18b708d0c6b8b11aeb4ace5f524b9be00870007/targets.cfg#L92

Found this in your code, but is there anywhere else where it would be?
https://github.com/xbmc/addon-check/blob/7b59cea63b7e8bf1021731d6312f4fc6b6189313/kodi_addon_checker/check_dependencies.py#L67

**Comment by anxdpanic** [comment]
https://kodi.wiki/view/Addon.xml#Dependency_versions

**Comment by anxdpanic** [comment]
Not that familiar with in the inner workings, but I assume it's https://github.com/xbmc/xbmc/blob/412dcbcd0827e99a20ca385b641e94d98317bf89/addons/xbmc.python/addon.xml#L2

**Comment by ReenigneArcher** [comment]
Thank you! Much appreciated!
