### ISSUE TITLE
Auto comment found issues on the PR

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#27]
When there are issues found it would be nice they would be automatically added as comment on the PR. If need accompanied with url to some helpful page.

**Comment by Razzeee** [comment]
As bulk as one comment or split and on affected line of the file? Pretty different problem. Also we probably need to store our secret somewhere, will have to look if travis is able to do that for us. As the rest is open source.

This seems helpful for the secret stuff: https://damien.pobel.fr/post/github-api-from-travisci/
And this library is the most popular github api for python: https://github.com/PyGithub/PyGithub

**Comment by MartijnKaijser** [comment]
Whatever is easiest which will probably be a bulk comment.

**Comment by Razzeee** [comment]
Yes, spares us quite some work

**Comment by Razzeee** [comment]
I just merged that 🥇
