### ISSUE TITLE
XML and JSON file check broadness

### ISSUE THREAD

**Issue by pannal** [xbmc/addon-check#275]
Hey,

The current implementation of the XML and JSON validators look for filenames _containing_ ".xml" or ".json", instead of checking whether the extension actually is the right one (`endswith`, or `os.path.splitext()[1]`).

This leads to issues with for example templating languages: I can't name my template "test.xml.tpl", or "test.xml.jinja2".

As those file would never even be "executed"/parsed as XML or JSON, I think the filename check is too broad.

**Comment by razzeee** [comment]
We still need a real xml file to do the schema validation https://github.com/xbmc/addon-check/tree/master/kodi_addon_checker/xml_schema

**Comment by razzeee** [comment]
We obviously won't do that. But whatever get's commited to an addon repo, needs to be a xml - kodi or the repo servers doesn't understand jinja2 or other markups.

**Comment by razzeee** [comment]
What you mean, is this check https://github.com/xbmc/addon-check/blob/440a545eeae6d2410a254c1517d20de01e1de144/kodi_addon_checker/check_files.py#L27 and https://github.com/xbmc/addon-check/blob/440a545eeae6d2410a254c1517d20de01e1de144/kodi_addon_checker/check_files.py#L42 which are too broad
