### ISSUE TITLE
Check for addon version bump

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#28]
Might be an edge case but check if there's an actual version bump done in addon.xml

**Comment by mzfr** [comment]
I think we can do that by using versionbump package from python ?

**Comment by Razzeee** [comment]
I don't think that will cover our problem :)

Have you written a kodi plugin/addon? There is a file `addon.xml` which is an xml and has infos about the version. We need to match this against the list coming from our servers and see if the PR has a higher version that the server.

**Comment by Rechi** [comment]
`http://mirrors.kodi.tv/addons/<KODI-VERSION>/addon.xml(.gz)`

**Comment by MartijnKaijser** [comment]
Why pull the full repo list for just comparing the addon.xml?
If you would pull addons.xml you would need to combine it with dependency check

**Comment by Razzeee** [comment]
Ther alternative is to look through each branch for a matching addon and check if any of those branches/addons has a higher version. So you need to checkout each branch and do a complete search.

**Comment by mzfr** [comment]
@Razzeee I think this issue was also covered by #57
