### ISSUE TITLE
Check for dependency issues

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#29]
Maybe it's possible to check the included dependencies in addon.xml against the repo it's PRed to.
For this you could parse the repo addons.xml (or first download/unzip the addons.xml.gz)

**Comment by mzfr** [comment]
what will be the next step after finding dependencies from addon.xml file ?

**Comment by MartijnKaijser** [comment]
sounds too complicated
You just need to check is current version is lower than new version. Simple string compare

**Comment by Razzeee** [comment]
I think @MartijnKaijser mixed up these tickets :)

**Comment by Razzeee** [comment]
so first step for this, would be to make our code aware of these urls (here are some examples, there's one for each version):

http://ftp.snt.utwente.nl/pub/software/xbmc/addons/gotham/addons.xml
http://ftp.snt.utwente.nl/pub/software/xbmc/addons/isengard/addons.xml
http://ftp.snt.utwente.nl/pub/software/xbmc/addons/leia/addons.xml

These include all addons, resources, skins etc. so it's a complete list with everything that's available for a version.

So if a PR targets the branch leia, it should download the leia addons.xml. Then check the versions of the dependencies in the addon.xml of the branch that's PRed. Here's an example this line https://github.com/xbmc/repo-scripts/blob/jarvis/script.trakt/addon.xml#L5 says we need script.module.simplejson in the version 3.3.0. If that's available all is fine, if not send a warning.

Not 100% sure which mirror would be the best here, but we can easily change that later on.

**Comment by Rechi** [comment]
What's wrong with using mirrors.kodi.tv to always get the best mirror?

**Comment by Razzeee** [comment]
Nothing, I keep forgetting the url and that's the one my browser remembered :suspect:

**Comment by mzfr** [comment]
@Razzeee This issue is fixed by PR #63. We can close this issue now.
