### ISSUE TITLE
Check screenshots for transparency

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#30]

**Comment by mzfr** [comment]
Hi, I'm new to the project and am looking for an issue to fix. Can you provide some more info on this?

**Comment by Razzeee** [comment]
So we already check icons for transparency here https://github.com/xbmc/addon-check/blob/master/check_addon.py#L192-L193

So this needs to be also done for the screenshot type of images which currently ends up in an else block here https://github.com/xbmc/addon-check/blob/master/check_addon.py#L208

The catch is, that screenshots can be other file types then png which the method from above is tested for.
So we need to handle the whole other bunch. 

@MartijnKaijser @tamland @Rechi Another worthy discussion would be to just disallow anything for screenshots other than `.jpg` as that's probably the best fit here.

**Comment by mzfr** [comment]
@Razzeee Screenshots doesn't have transparency because they only have RGB value and no alpha in it.
Also if someone edits the screenshot using an editor and then adds alpha value to it then we are already having a check for that.

Another option could be to define a size for acceptable screenshots. We can choose any size like size of fanart (1280, 720) or size of an image(256, 256). Then we can have our normal checks run on them.

**Comment by mzfr** [comment]
Do we still need to worry about this ?

**Comment by Razzeee** [comment]
If you would have asked me today I would have thought, that we demand on screenshots being `jpg`. @enen92 
If we do, we could check for that, but might not be that important.

**Comment by enen92** [comment]
they normally are jpegs just like the fanart

**Comment by Razzeee** [comment]
They normally are, but do we enforce that in the guidelines? I think we should.

**Comment by Rechi** [comment]
For repo-plugins, krypton branch, it isn't sometimes, as there are more png screenshots then jpg ones.
```
$ git grep -e '\.png' --and -e screenshot */addon.xml | wc -l
137

$ git grep -e '\.jpg' --and -e screenshot */addon.xml | wc -l
82
```

**Comment by Razzeee** [comment]
Then we still worry about this.

**Comment by mzfr** [comment]
Any thoughts on my previous [comment](https://github.com/xbmc/addon-check/issues/30#issuecomment-385192802)?

**Comment by Razzeee** [comment]
We just want to run the transparency check we already have on screenshots.

**Comment by mzfr** [comment]
Okay but our `has_transparency` code check whether the image mode is `RGBA` or not. And as I said in my previous comment screenshot doesn't have `RGBA` they only have `RGB` values. So even if we run our check on screenshot it will always `return False`.

**Comment by Razzeee** [comment]
Pretty sure `png` has an alpha channel
