### ISSUE TITLE
Verify addon.xml against a xml schema

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#33]
I don't think we have a schema but we could create one.

**Comment by MartijnKaijser** [comment]
You mean something like this?
https://github.com/xbmc/xbmc/blob/master/addons/xbmc.python/pluginsource.xsd

**Comment by Razzeee** [comment]
Yes

**Comment by mzfr** [comment]
I can do it if you can give some guide line about what type of schema will be required ?

**Comment by Razzeee** [comment]
Well I would probably try to use http://lxml.de/validation.html to load the xsd martijn linked above and validate the addon.xml with that.

**Comment by MartijnKaijser** [comment]
There are several more of these in our repo for each type

**Comment by mzfr** [comment]
I think using [xmlschema](https://pypi.python.org/pypi/xmlschema) would make this much simply.
what do you think @Razzeee @MartijnKaijser ?

**Comment by Razzeee** [comment]
Sounds good, not sure why I didn't find that package 😆

**Comment by mzfr** [comment]
Should I use only [This](https://github.com/xbmc/addon-check/issues/33#issuecomment-364636443) schema or should I use any other schema for verifying addon.xml

**Comment by MartijnKaijser** [comment]
https://github.com/xbmc/xbmc/tree/master/addons  contains several more schemes in the folder for eacht type of addon so the one matching should be found and used

**Comment by mzfr** [comment]
Another thing, Is there any channel where I can ask questions from @Razzeee or from you about the small queries I have.
Commenting here isn't that good

**Comment by MartijnKaijser** [comment]
irc #kodi-dev

**Comment by mzfr** [comment]
Actually i message [This](https://github.com/xbmc/addon-check/issues/33#issuecomment-365307711) over there but no-one replied that's why i was asking
