### ISSUE TITLE
Reformatting the code according to PEP style guide.

### ISSUE THREAD

**Issue by AdityaGupta030697** [xbmc/addon-check#39]
The code in check _addon.py, check_repo.py and common.py needs to be reformatted according to PEP 8 style guide along with some improvements in code like removing unnecessary parenthesis.
Please let me know if this sounds reasonable and I can start working on a pull for this!
Regards
Aditya

**Comment by Razzeee** [comment]
Sure, I do this regulary but might have forgotten about this the last times.

**Comment by AdityaGupta030697** [comment]
okay

**Comment by AdityaGupta030697** [comment]
It has to be done again after the recent commits.
