### ISSUE TITLE
Cleaner command-line interface

### ISSUE THREAD

**Issue by mzfr** [xbmc/addon-check#40]
Currently, we use the tool for running on Travis so that addon pull requests can get validated. Any found errors get logged on Travis which developers can see and fix.

I was wondering if it would make sense to package the tool for consumption by addon developers so that they can run it directly on their machine **before** submitting a PR. This will help in reducing the feedback loop. 

Not a lot of changes are required for this, we just need to have a cleaner CLI entry point since there are two files `check_addon.py` and `check_repo.py` and it might not be entirely obvious to other users which one needs to be run and how.

We could add a simple CLI using `argparse` into a file (maybe called `check.py`) which the users could run then we could just upload it to PyPI from where users could download this.

What do you think?

**Comment by Razzeee** [comment]
Yes, it's actually intended to serve these cases:
- Being run on the repo by us or any third party
- Being run by a developer on his local system to see errors in advance.

I ment to update the readme to reflect that vision but haven't managed yet.
In theory you should be able to run check_addon.py with a param and it should check your addon. Haven't done that in some days, but that's mostly the reason for the two files seperation in the first place.

**Comment by Razzeee** [comment]
Sounds like a plan

**Comment by Razzeee** [comment]
Also interesting would be if we can use this to write a vscode plugin/linter.

**Comment by mzfr** [comment]
Do we need any changes in our current command-line interface ?

**Comment by Razzeee** [comment]
I think this is fine.
