### ISSUE TITLE
add 3840x2160 fanart as accepted in the check

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#42]

**Comment by mzfr** [comment]
Can you point me to the plugin thread where this fanart issue occurred?

**Comment by MartijnKaijser** [comment]
Just need to be added here
https://github.com/xbmc/addon-check/blob/master/check_addon.py#L206

https://travis-ci.org/xbmc/repo-plugins/builds/345365652?utm_source=github_status&utm_medium=notification
