### ISSUE TITLE
detect incorrectly set file permissions

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#43]
Some accidentally set wrong file permissions while submitting

**Comment by mzfr** [comment]
@martijn It's not really clear which permissions are to be considered incorrect? and what to do after detecting them?

**Comment by Razzeee** [comment]
Well you can only report them as we have no write access to the gits of the submitting party. Not sure what permissions are problematic, will have to wait for @MartijnKaijser

**Comment by Rechi** [comment]
As no scripts submitted in an addon has to be stand-alone executable, they never should be marked executable. (allowed: 644, not allowed everything else).

For most PR we could change the commits (https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/), but why should we want that?

**Comment by mzfr** [comment]
@Razzeee So all we have to do in this is that whether the python files submitted in a PR are marked as executable or not ??

**Comment by MartijnKaijser** [comment]
yes

**Comment by mzfr** [comment]
Okay I'll work on this one
