### ISSUE TITLE
Think about creating a pip package from this

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#45]
I have never done a pip package so far, but it might work for us if we can use pipenv to run this.

**Comment by slgobinath** [comment]
Hi,
Currently, I am working on this. Do you have a preferred universal name for addon-checker?
The name must be unique across Python packages available in [pypi](https://pypi.python.org/pypi) and can be used as the terminal command.

WDYT about `kodi-addon-checker`?

**Comment by Razzeee** [comment]
Name sounds fine.
Code also looks good, but I've got no time right now to try it out. From my understanding that's what we need to push it to pypi?
Btw, we will have to change the author and email in the long run.

**Comment by slgobinath** [comment]
Sure.
Please let me know the author name and email to use. I will update them and send a PR after testing on Windows.

FYI: Following this [tutorial](https://www.codementor.io/arpitbhayani/host-your-python-package-using-github-on-pypi-du107t7ku) I published my personal project to pypi.

**Comment by Razzeee** [comment]
Please use `Team Kodi` as author, email is mandatory right?
We ultimatly want to push that package to pypi as Kodi with a Kodi account I guess.
See https://github.com/xbmc/addon-check/issues/49 please

**Comment by slgobinath** [comment]
Author name and email are not mandatory. So I ignore the email but include `Team Kodi` as the author.
License field also skipped until we pick a license.

**Comment by slgobinath** [comment]
I have tested setup.py installation on Linux Mint and Windows. Everything works as expected in my testing.
Please see the PR #50 

Thanks

**Comment by mzfr** [comment]
@Razzeee since we now have a pip package, All thanks to @slgobinath. I think we can close this issue now.
