### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#49]
Somehow I forgot to include a license 🤦‍♂️

**Comment by slgobinath** [comment]
KODI is released under GPL v2.
If this add-on will be packaged with KODI (may be in future), we need to release this add-on under GPL v2. If not, I vote for GPL v3 which is recommended by GNU.

For more details: https://www.gnu.org/licenses/rms-why-gplv3.en.html

**Comment by Razzeee** [comment]
I don't see a reason to ship it with kodi. So it's basically going to be MIT or GPL v3, if you ask me.

**Comment by mzfr** [comment]
@Razzeee this issue is resolved now right ?

**Comment by Rechi** [comment]
license added at #52
