### ISSUE TITLE
Check for git related files

### ISSUE THREAD

**Issue by enen92** [xbmc/addon-check#55]
A common issue when people submit addons to the repository is the presence of a `.git` folder, a `.gitignore` or `.gitattributes` file in the PR. The addon-check tool should look for the presence of such files and automatically inform the user to remove them from the pull request.

**Comment by Razzeee** [comment]
I get the `.git` folder, not 100% sold on the other two. Especially the `.gitignore`

**Comment by Rechi** [comment]
Git didn't allow me to stage a `.git` folder in a subdirectory to (also tried with the force option).
Why do you want to forbid `.gitignore` and `.gitattributes` files?

**Comment by enen92** [comment]
It has always been a rule to ask for the removal of such files in the pull requests. Probably something related to the script that builds the zip files for each updated addon? If this is not a rule for the repository than we should stop asking people to remove them.

**Comment by Rechi** [comment]
[repository generator](https://github.com/xbmc/repository-generator) doesn't have an issue if those files are present.

**Comment by enen92** [comment]
Yes it looks like they are ignored and not part of the produced zip @Rechi. We should stop requesting removal of such files in submissions. Thanks for the heads up.

**Comment by Razzeee** [comment]
Btw I even scripted this addon-checker to not report `.gitignore` :)

**Comment by Razzeee** [comment]
I think this is solved by our workflow then.
