### ISSUE TITLE
Check if addon is already present in a lower repository

### ISSUE THREAD

**Issue by enen92** [xbmc/addon-check#56]
This issue is a suggestion.

I have seen many cases in which a user submits an addon to a repository (lets say Krypton) and the addon is already present in "lower" repositories (e.g. helix). In those cases the check-tool should produce a warning to inform the user of this fact since most of the time the user is either not aware of the presence of the addon in a lower repo, doesn't know recent versions still have access to those lower repos, the changes are so minimal that do not justify a full addon review or the changes are not version specific. 
Finding if the addon already exists in another repo is both a memory exercise or a manual checking step (time consuming) and preferably should be avoided.

**Comment by Razzeee** [comment]
Can be done via https://github.com/xbmc/addon-check/pull/51 and a simple print output. Not warn or error.

**Comment by enen92** [comment]
Fine. Main goal is to inform the user so it does not need to be a warning. Please close if already addressed.

**Comment by Razzeee** [comment]
@mzfr

**Comment by mzfr** [comment]
@Razzeee So should I just add this to #51 itself? This would just involve downloading addon.xml for all branches and seeing if the same addon id exists in any of them, right?

**Comment by Razzeee** [comment]
Yeah, I will leave it up to you if you want to do it in #51 or in a follow up. I would also print the version of the addon in the lower branches.

**Comment by enen92** [comment]
@mzfr @Razzeee I’d also check if the version in those lower repos has the broken element set in addon.xml.

**Comment by mzfr** [comment]
@Razzeee I will make a new PR for this issue.

**Comment by enen92** [comment]
@mzfr it is a common practice to mark addons as broken when they stop working or are no longer maintained. This is achieved by setting the <broken></broken> element in addon.xml with a message explaining the reasoning (of the addon being broken). Consider the use case in which an addon exists in a lower Repo (Gotham) and was marked as broken due to  being no longer maintained. If someone decides to take the ownership of the said addon, to fix it and submit it to krypton there is no reason for the CI to flag any "issue". 

Recently i marked one of my addons (screensaver.atv4) as broken in the helix Repo and moved it to krypton as it is a skinned addon and required methods introduced in the skinning API with krypton. Being " warned" with each update I send from now on due to an outdated and explicitly tagged broken addon present in helix does not make much sense.
Hope the explanation was clear enough.

**Comment by mzfr** [comment]
@enen92  Yes it is clear now Thank you for explaining it. Just one thing Can you please provide link to the broken addon you mention so I can have a look of how a broken addon would look like(I have never seen any broken xml file before).

**Comment by enen92** [comment]
Sure. The broken one: https://github.com/xbmc/repo-scripts/tree/helix/screensaver.atv4

The updated one: https://github.com/xbmc/repo-scripts/tree/krypton/screensaver.atv4

Sorry for the wrong identation of the first addon.xml.

**Comment by mzfr** [comment]
@enen92 for this we can just check for a `<broken>``</broken>` tags.

Also for broken addons should we print something like `<addon_name> exists in <repo_name> but is broken` or we shouldn't print anything at all ?

**Comment by enen92** [comment]
Yes checking for "broken" element in addon.xml is the only step needed. Up to you, since it has an INFO/NOTICE level any option is okay. Probably logging it could still be usefull just as a means of checking if credits should (in therory...) still be given to the original author or if the addon is a full re-write

**Comment by Razzeee** [comment]
+1 on logging it

@mzfr sure, do a log entry if it's a new addon. so we woud have some kind of interaction in each case
