### ISSUE TITLE
Check for __init__.py

### ISSUE THREAD

**Issue by mzfr** [xbmc/addon-check#71]
We Should have a check for __init__.py file.
The main reason is that When we run pylint on any folder it first checks for __init__.py file in it. If the file is missing then it produce an error

This is the error:
![screenshot_20180505_202420](https://user-images.githubusercontent.com/16623935/39664547-6be9b7d4-50a2-11e8-975a-7b51fb4fee56.png)

This is a [know problem](https://github.com/PyCQA/pylint/issues/352) in pylint.

**Comment by Razzeee** [comment]
I would rather hope for them to fix it then add this hack to our codebase :/
Pretty much every addon will fails that check, as you only need that file for subfolders in kodi land.

**Comment by mzfr** [comment]
We don't need this anymore
