### ISSUE TITLE
Update ignored list of pseudo addons for dependency detection

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#83]
We will never be able to find these addons in any repo.

So let's ignore all of these:
https://github.com/xbmc/xbmc/blob/2f9feb2/xbmc/addons/AddonInfo.cpp#L39-L77

**Comment by Razzeee** [comment]
This would actually be version dependent, so we need to ignore different stuff depending on our branch config.

**Comment by mzfr** [comment]
@Razzeee What I was able to understand from this was:

We have an [ignore list](https://github.com/xbmc/addon-check/blob/master/kodi_addon_checker/check_addon.py#L414) now all we have to do is to add all this into ignore list 

Now what I don't understand was `This would actually be version dependent, so we need to ignore different stuff depending on our branch config.` this statement. What would be version dependent ?

**Comment by mzfr** [comment]
@Razzeee okay so I have to just add all these names into that ignore list right ? 

> And later do the version dependent side of it. The ignore list theoretically needs to be specific to each version of Kodi, as the code could have changed with each version. 

okay so that means we should have different ignore list for different branch.
Eg: 
```
jarvis_ignore_list = [<some addon name>]
krypton_ignore_list = [<some addon name>]
```

> In practice, it's probably even better if we don't allow the reserved names in any repo.

By reserved name you mean the names mentioned in the list you mentioned above. Like `xbmc.metadata.scraper.albums` etc ? 
Also what do mean by "in any repo" ? how are these name used in repo's

**Comment by Razzeee** [comment]
Yes, just add all the names from the list.

Basically that's all that this needs to be solved.

Ignore the rest, it's not important.
